id = "dowe"
name = "Dowe"
description = "Dowe Source Format support for Zed."
version = "0.1.0"
schema_version = 1
authors = ["Dowe Contributors"]
repository = "https://github.com/usedowe/dowe-zed"
languages = ["languages/dowe"]
capabilities = []

[lib]

[language_servers.dowe-language-server]
name = "Dowe Language Server"
languages = ["Dowe"]

[language_servers.dowe-language-server.language_ids]
"Dowe" = "dowe"

[grammars.dowe]
repository = "file:///Users/varb/Work/dowe/dowe-zed/.zed-dev/tree-sitter-dowe.git"
rev = "b0248b16393ff39d939cb49946062f97ec1af395"

[context_servers]

[agent_servers]

[slash_commands]
