id = "dowe"
name = "Dowe"
description = "Dowe Source Format support for Zed."
version = "0.1.0"
schema_version = 1
authors = ["Dowe Contributors"]
repository = "https://github.com/usedowe/dowe-zed"
languages = ["languages/dowe"]
capabilities = []

[lib]

[language_servers.dowe-language-server]
name = "Dowe Language Server"
languages = ["Dowe"]

[language_servers.dowe-language-server.language_ids]
"Dowe" = "dowe"

[grammars.dowe]
repository = "https://github.com/usedowe/dowe-zed"
rev = "23fd2ff4f73c1f65ab54511bade13605ff5f0463"
path = "tree-sitter-dowe"

[context_servers]

[agent_servers]

[slash_commands]
